<?php

namespace App\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CarModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarModelRepository extends EntityRepository
{
}
