App\Entity\Advertisement:
  type: entity
  table: advertisement
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    content:
      type: string
      length: 16777215
      nullable: true
    description:
      type: string
      length: 255
      nullable: true
    dateCreate:
      type: datetime
    dateUpdate:
      type: datetime
    carId:
      type: integer
      length: 16
    userId:
      type: integer
      length: 16
      nullable: true
    price:
      type: integer
      length: 16
  oneToOne:
    car:
      targetEntity: Car
      inversedBy: ads
      joinColumn:
        name: carId
        referencedColumnName: id
