App\Entity\Advertisement:
  type: entity
  table: advertisement
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    content:
      type: string
      length: 16777215
    description:
      type: string
      length: 255
    create:
      type: date
    update:
      type: date
    car_id:
      type: integer
      length: 16
    user_id:
      type: integer
      length: 16
