App\Entity\CarBrand:
  type: entity
  table: car_brand
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 42
  oneToMany:
    cars:
      targetEntity: Car
      mappedBy: brand
    models:
      targetEntity: CarModel
      mappedBy: brand