App\Entity\Role:
  type: entity
  table: role
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 42
  oneToMany:
    users:
      targetEntity: User
      mappedBy: role